### ISSUE TITLE
Error towards the end of every command

### ISSUE THREAD

**Issue by ivishalgandhi** [gkssjovi/taskmd#1]
taskmd project:work:inbox

markdown output 

TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: { encoding: 'utf8' }
    at new NodeError (node:internal/errors:371:5)
    at _write (node:internal/streams/writable:294:13)
    at Socket.Writable.write (node:internal/streams/writable:335:10)
    at copy (/Users/vishalgandhi/utilities/taskmd/src/main.js:49:16)
    at main (/Users/vishalgandhi/utilities/taskmd/src/main.js:78:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_UNKNOWN_ENCODING'
}

**Comment by gkssjovi** [comment]
I think this is from `pbcopy` that copies the output to the console.
I did some changes, please try again now.
Also you can put the flag --copy false

**Comment by ivishalgandhi** [comment]
Thank you --copy works. How do i update the main.js ? do i need to clone the repo again ?

**Comment by gkssjovi** [comment]
You will need to clone or pull te repository again.
But I usually have a folder called `~/dev` or `~/tools` under the home directory, and I clone the repositories there.
Then I link the `main.js` to the bin directory `/usr/local/bin`
`ln -s $PWD/src/main.js /usr/local/bin/taskmd`
And when I want to update the package I just make a `git pull` request under the `~/dev/taskmd` folder.
For the default configuration you can do to following.
```sh
cp config.yaml  personal.config.yaml
mkdir ~/.config/taskmd/
ln -s $PWD/personal.config.yaml ~/.config/taskmd/config.yaml 
```

Then you can modify this file `~/.config/taskmd/config.yaml` and write your visible columns and other options.
